"""Debug-style Source tests.

This intentionally does not use pytest. Run one scenario with:

    python tests/sources/sources.test.py --test fresh-source

Or run every scenario with:

    python tests/sources/sources.test.py --test all
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Callable

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from backend.modules.sources import Source, SourceDefinition, source
from backend.modules.sources.column_info.finder.discovery_engine import discover_metadata


def _write_csv(path: Path, rows: list[dict]) -> None:
    pd.DataFrame(rows).to_csv(path, index=False)


def _source_definition(path: Path, key: str = "debug_source") -> SourceDefinition:
    return SourceDefinition(
        source_key=key,
        display_name=f"Debug Source {key}",
        category="debug",
        connector_type="csv",
        source_url=str(path),
        notes="Local CSV generated by tests/sources/sources.test.py",
    )


def _make_source() -> tuple[TemporaryDirectory, Source, str]:
    temp_dir = TemporaryDirectory()
    csv_path = Path(temp_dir.name) / "debug_source.csv"
    _write_csv(
        csv_path,
        [
            {"name": "alpha", "value": 10, "category": "a", "latitude": 42.1, "longitude": -121.1},
            {"name": "beta", "value": 20, "category": "b", "latitude": 42.2, "longitude": -121.2},
            {"name": "gamma", "value": 30, "category": "a", "latitude": 42.3, "longitude": -121.3},
        ],
    )
    key = "debug_source"
    return temp_dir, source(_source_definition(csv_path, key)), key


def test_fresh_source() -> None:
    """Load a fresh source directly to Source."""
    temp_dir, data_source, key = _make_source()
    try:
        df = data_source.dataframes[key]
        print("[fresh-source] sources:", list(data_source.dataframes))
        print("[fresh-source] shape:", df.shape)
        print("[fresh-source] first row:", df.iloc[0].to_dict())
    finally:
        temp_dir.cleanup()


def test_metadata_analysis() -> None:
    """Retrieve metadata from the analyzer."""
    temp_dir, data_source, key = _make_source()
    try:
        data_source.generate_metadata()
        columns = data_source.metadata[key]["columns"]
        print("[metadata-analysis] profiled columns:", [col["name"] for col in columns])
        print("[metadata-analysis] first profile:", columns[0])
    finally:
        temp_dir.cleanup()


def test_metadata_finder() -> None:
    """Try to access metadata using the finder."""
    documentation_url = discover_metadata(
        source_key="demo_socrata",
        source_url="https://data.oregon.gov/resource/fa7z-shhx.csv",
        connector_type="csv",
    )
    print("[metadata-finder] discovered documentation URL:", documentation_url)


def test_index_notation() -> None:
    """Try accessing values using source/key/column index notation."""
    temp_dir, data_source, key = _make_source()
    try:
        values = data_source[key]["value"].resolve().tolist()
        print("[index-notation] value column:", values)
    finally:
        temp_dir.cleanup()


def test_column_names() -> None:
    """Try accessing columns by names and integer IDs."""
    temp_dir, data_source, key = _make_source()
    try:
        print("[column-names] colids:", data_source.colids(key))
        print("[column-names] names:", data_source.names({key}))
    finally:
        temp_dir.cleanup()


def test_column_names_and_index() -> None:
    """Try accessing using column names and row/column index notation."""
    temp_dir, data_source, key = _make_source()
    try:
        indexed = data_source.index(**{key: ("0..2", "name,value")})
        print("[column-names-index] indexed frame:", indexed.dataframes[key].to_dict(orient="records"))
    finally:
        temp_dir.cleanup()


def test_add_column() -> None:
    """Test adding a computed column to the source."""
    temp_dir, data_source, key = _make_source()
    try:
        data_source.add((key, "double_value"), f"{key}[value] * 2")
        print("[add-column] columns:", data_source.dataframes[key].columns.tolist())
        print("[add-column] double_value:", data_source.dataframes[key]["double_value"].tolist())
    finally:
        temp_dir.cleanup()


def test_add_row() -> None:
    """Test adding a row to the source dataframe."""
    temp_dir, data_source, key = _make_source()
    try:
        row = {"name": "delta", "value": 40, "category": "c", "latitude": 42.4, "longitude": -121.4}
        data_source.dataframes[key] = pd.concat([data_source.dataframes[key], pd.DataFrame([row])], ignore_index=True)
        print("[add-row] row count:", len(data_source.dataframes[key]))
        print("[add-row] last row:", data_source.dataframes[key].iloc[-1].to_dict())
    finally:
        temp_dir.cleanup()


def test_two_sources() -> None:
    """Load two fresh sources into a single Source."""
    temp_dir = TemporaryDirectory()
    try:
        first_csv = Path(temp_dir.name) / "first.csv"
        second_csv = Path(temp_dir.name) / "second.csv"
        _write_csv(first_csv, [{"name": "alpha", "value": 1}, {"name": "beta", "value": 2}])
        _write_csv(second_csv, [{"name": "gamma", "score": 5}, {"name": "delta", "score": 8}])
        data_source = Source(_source_definition(first_csv, "first")).add_source(_source_definition(second_csv, "second"))
        print("[two-sources] sources:", list(data_source.dataframes))
        print("[two-sources] shapes:", {key: df.shape for key, df in data_source.dataframes.items()})
    finally:
        temp_dir.cleanup()


def test_generate_charts() -> None:
    """Test generating charts from source expressions."""
    temp_dir, data_source, key = _make_source()
    try:
        chart_path = Path(temp_dir.name) / "debug_scatter.png"
        chart = data_source.scatter(data_source[key]["longitude"], data_source[key]["latitude"])
        visual = chart.save(str(chart_path))
        print("[generate-charts] visual path:", visual.path)
        print("[generate-charts] legend entries:", visual.legend.entries)
        print("[generate-charts] file exists:", chart_path.exists())
    finally:
        temp_dir.cleanup()


TESTS: dict[str, Callable[[], None]] = {
    "fresh-source": test_fresh_source,
    "metadata-analysis": test_metadata_analysis,
    "metadata-finder": test_metadata_finder,
    "index-notation": test_index_notation,
    "column-names": test_column_names,
    "column-names-index": test_column_names_and_index,
    "add-column": test_add_column,
    "add-row": test_add_row,
    "two-sources": test_two_sources,
    "generate-charts": test_generate_charts,
}


def run_test(name: str) -> None:
    print(f"\n=== running {name} ===")
    TESTS[name]()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run debug Source tests with printed outputs.")
    parser.add_argument("--test", choices=["all", *TESTS.keys()], default="all", help="Test scenario to run.")
    args = parser.parse_args()

    if args.test == "all":
        for name in TESTS:
            run_test(name)
    else:
        run_test(args.test)


if __name__ == "__main__":
    main()
# Doesn't use pytest but is a normal standard python file with real debug outputs
# Called by python -m source




# Here are the test scenarios placed into individual functions with each action debugged output

# Load a fresh source directly to source
# Retrieve the metadata from the analysis 
# Try to access the metadata using the finder
# Try accessing using index notation 
# Try accessing using the column names
# Try accessing using the column names and index notation
# Try accessing using the column names and index notation

# Test adding a column to the source
# Test adding a row to the source


# Load two fresh sources into a single source

# Test generating charts